   class Question {
 constructor(text, choices, answer){
    this.text = text;
    this.choices = choices;
    this.answer = choices[answer-1]; 
   }
   isCorrectAnswer = function(choice) { 
    return this.answer === choice;
  }
}  
 
 
 var questions = [new Question("What does the following function do?<br><br><div class='codetext'>int foo(int m)<br>{<br> if(m)<br> {<br>&nbsp;&nbsp;return m%10  +foo(m/10);<br>&nbsp;&nbsp;}<br>}<br><br></div>",["Returns the remainder when m is divided by 10","Gives run time error","Returns sum of digits of the number","None of the the above"],3),
new Question("What does this function do?<br><br><div class='codetext'>void print(char *str)<br>{<br>&nbsp;&nbsp;  print(str+1);<br>&nbsp;&nbsp;  putchar(*str);<br>}<br></div>",["Prints the string in reverse order","Prints the string in correct order. ","Runs infinitely","None of the above"],3),
new Question("What does this code print?<br><br><div class='codetext'>int squre(int m)<br>{<br>&nbsp;&nbsp;return m*m;<br>}<br>int main()<br>{<br>&nbsp;&nbsp;int z=12;<br>&nbsp;&nbsp;  square(z);<br>&nbsp;&nbsp;  printf('%d',z);<br>} <br></div>",["Prints 144","Syntax error.  ","Prints 12","None of the above"],3),
new Question("Write a code to return two values from a function, a and b.   ",["return a; return b;","return a,b;","A function can not return 2 values","None of the above"],3),
new Question("Which of these two functions correctly swaps 2 variables ?<br><br><div class='codetext'>void swap(int a,int b)<br>{<br>&nbsp;&nbsp;a=a+b;<br>&nbsp;&nbsp;b=a-b;<br>&nbsp;&nbsp;a = a-b;<br>}<br><br>void swap(int *a,int *b)<br>{<br>&nbsp;&nbsp;  *a = *a+*b;<br>&nbsp;&nbsp;  *b=*a-*b;<br>&nbsp;&nbsp;  *a=*a-*b;<br>}<br></div>",["First function","Second function","Neither. You should use exor operator to swap two variables",""],2),
new Question("A function is written to add all elements of the array. Find out the lines containing errors<br><br><div class='codetext'>1   void  sum_of_array(int *arr,int n)<br>2    {<br>3       int s;<br>4        int i;<br>5        while(i<n)<br>6              s+=arr[i++];<br>7        return s;<br>8     }<br></div>",["1 3 4 6","1 3 4","No errors","Only 6"],2),
new Question("Which of these can not be the return type of a funciton?   ",["pointer","array","structure","None of these"],2),
new Question("What does the following function do?<br><br><div class='codetext'>int Trial (int a, int b, int c)<br>{<br>if ((a >= b) && (c < b)) return b;<br>else if (a >= b) return Trial (a,c,b);<br>else return Trial (b,a,c);<br>}<br></div>",["Finds maximum of a,b,c","Finds minimum of a,b,c","Finds middle number of a,b,c","None of these"],3),
new Question("Which of these functions prints all the elements of an array?   ",["<span class='codetext'>void foo(int *ptr,int n)<br>{<br>&nbsp;&nbsp;  int i;<br>&nbsp;&nbsp;  for(i=0;i<n;i++,ptr++)<br>&nbsp;&nbsp;      printf('%d',*ptr);<br></span> }","<span class='codetext'>void bar(int arr[],int n)<br>{<br>&nbsp;&nbsp;    while(n)<br>&nbsp;&nbsp;        printf('%d\n',arr[--n]);<br></span> }","Neither of these","Both"],4),
new Question("What does this function do?<br><br><div class='codetext'>int fn1(int x,int y)<br>{<br>&nbsp;&nbsp; if(y>0)<br>&nbsp;&nbsp;     return x*fn1(x,y-1);<br>&nbsp;&nbsp; else<br>&nbsp;&nbsp;     return 1;<br>}<br></div>",["Returns the product of 2 numbers","Returns first number","Returns first number raised to the power of second number","None of these"],3),
new Question("Recursive functions are executed in ---- order   ",["First In First Out","Last In First Out","All of these",""],2),
new Question("What is the return value of the function foo when it is called as foo(345,10) ?<br><br><div class='codetext'> int foo( int n,  int r)<br> {<br>&nbsp;&nbsp;   if (n > 0)<br>&nbsp;&nbsp;      return (n%r + foo (n/r, r ));<br>&nbsp;&nbsp;  else<br>&nbsp;&nbsp;      return 0;<br>&nbsp;&nbsp;}<br></div>",["345","5","12","3"],3),
new Question("With the following definition of swap function, how should tbe function be called to exchange the values of two variables?<br><br><div class='codetext'>void swap (int *p1, int *p2)<br>{<br>&nbsp;&nbsp;  int temp;<br>&nbsp;&nbsp; temp = *a;<br>&nbsp;&nbsp;  *a = *b;<br>&nbsp;&nbsp;  *b = temp;<br>}<br></div>",["swap (x, y)","swap (&x, &y)","Both 1 and 2","None of the above"],2),
new Question("Two functions are written to find n<sup>th</sup> term of fibonacci seris. Which one is correct?<br><br><div class='codetext'>int fib1(int term)<br>{<br>&nbsp;&nbsp; if(term>1)    return fib(term-1)+fib(term-2);<br>&nbsp;&nbsp; else<br>&nbsp;&nbsp;      if(term==1)<br>&nbsp;&nbsp;           return term;<br>}<br><br>int fib2(int term)<br>{    int i=0,n1=0,n2=0,n;<br>&nbsp;&nbsp;  while(i<=term)<br>&nbsp;&nbsp; {<br>&nbsp;&nbsp;           if(i<2)<br>&nbsp;&nbsp;                 n  = i;       else       n = n1+n2;<br>&nbsp;&nbsp;          n2 = n1;       n1 = n;       i++;<br>&nbsp;&nbsp;    }<br> return n<br>}<br></div>",["fib1","fib2","Both","Neither"],3),
new Question("Which of the following library functions is an example of variable argument function?   ",["printf","scanf","strcpy","Both first and second"],4),
new Question("The function with a prototype given below is --------<br><br><div class='codetext'>void foo(int a,...);<br></div>",["Incomplete function","Syntactically incorrect function","Variable argument function","None of these"],3),
new Question("What is the output of this code?<br><br><div class='codetext'>int foo(int m)<br>{   static int a = 0;<br>&nbsp;&nbsp;   a+=5;<br>&nbsp;&nbsp;   return a;<br>}<br>int main()<br>{<br>&nbsp;&nbsp;  int s;   foo();foo();<br>&nbsp;&nbsp; s = foo();<br>&nbsp;&nbsp; printf('%d',s);<br>}<br></div>",["5","15","Syntax error","None of these"],2),
new Question("A function is written to find largest of three numbers. Find out the errors. <br><br><div class='codetext'>int largest(int a,b,c)<br>{<br>&nbsp;&nbsp;   if   (a>b && a>c)   return a;<br>&nbsp;&nbsp;   if   (b>a && b>c)   return b;<br>&nbsp;&nbsp;   return c;<br>}<br></div>",["A function can not have multiple return statements","The function header should be<span class='codetext'>int largest(int a,int b,int c)</span>","if statement should be followed by else statement","No errors"],2),
new Question("Find out errors in this function<br><br><div class='codetext'>int foo(int a)<br>{<br>register int b;<br>scanf('%d',&b);<br>return a+b;<br>}<br></div>",["<span class='codetext'>register int b;</span> is invalid statement","You can not add register variable to auto variable","You can not use address of (&) operator with register variable","No errors"],3),
new Question("What does the following function do?<br><br><div class='codetext'>int sum(int m,...)<br>{<br>&nbsp;&nbsp;int i;int sum=0;<br>&nbsp;&nbsp;va_list list;<br>&nbsp;&nbsp; va_start(list,m);<br>&nbsp;&nbsp;for(i=0;i<m;i++)<br> {<br> &nbsp;&nbsp;&nbsp;int a = va_arg(list,int);<br>&nbsp;&nbsp;&nbsp;sum+=a;<br>}<br>&nbsp;&nbsp;return sum;<br>}</div>",["Finds the sum of n number of parameters where n is given as first parameter","Gives syntx error in line 1","Finds the sum of command line arguments","None of these"],1),
new Question("What is the output of the following code?<br><br><div class='codetext'>void print_array(int arr[])<br>{    int i;<br>&nbsp;&nbsp;   for(i=0;i<size;i++)<br>&nbsp;&nbsp;         printf('%d',arr[i]);<br>}<br>int main()<br>{<br>&nbsp;&nbsp;  int arr[4]={5,6,7,8};<br>&nbsp;&nbsp;  int size = 4;<br>&nbsp;&nbsp;  print_array(arr);<br>&nbsp;&nbsp;  return 0;<br>}<br></div>",["5 6 7 8","Error because function is not declared","Syntax Error. size is not defined in function print_array",""],3),
new Question("What will be the output of the program?<br><br><div class='codetext'>void fun(char *msg, ...)<br>{<br>&nbsp;&nbsp;va_list ptr;<br>&nbsp;&nbsp;int num;<br>&nbsp;&nbsp;va_start(ptr, msg);<br>&nbsp;&nbsp;num = va_arg(ptr, int);<br>&nbsp;&nbsp;num = va_arg(ptr, int);<br>&nbsp;&nbsp;printf('%d', num);<br>}<br>int main()<br>{<br>&nbsp;&nbsp; fun('Hello world', 1, 4, 7, 11, 0);<br>&nbsp;&nbsp; return 0;<br>}<br></div>",["Hello world1","1","4",""],3),
new Question("What will be the output of this program?<br><br><div class='codetext'>void fun(...)<br>{<br>&nbsp;&nbsp;  va_list ptr;    int num;<br>&nbsp;&nbsp;  num = va_arg(ptr, int);<br>&nbsp;&nbsp;   printf('%d', num);<br>}<br>int main()<br>{    fun(3, 7, -11.2, 0.66);    return 0;<br>}<br></div>",["3","7","Syntax error  ",""],3),
new Question("What is the error in this code?<br><br><div class='codetext'>void display(char *s, int num1, int num2, ...)<br>{<br>&nbsp;&nbsp;  double c;    char s;<br>&nbsp;&nbsp;  va_list ptr;<br>&nbsp;&nbsp;  va_start(ptr, s);<br>&nbsp;&nbsp; c = va_arg(ptr, double);    printf('%f', c);<br>}<br></div>",["display function must be<span class='codetext'>void display(char *s,..)</span>","No error","<span class='codetext'>va_start(ptr, s);</span> must be va_start(ptr, num2);",""],3),
new Question("Find the error/s in this code.   <br><br><div class='codetext'>void foobar(int *,void *);<br>void foo()<br>{<br>&nbsp;&nbsp; int a; void b;<br>&nbsp;&nbsp; foobar(&a,&b);<br>}<br></div>",["You can not call a function from another function.","You can not define a variable of type void","No errors",""],2),
new Question("Which of the following statements  is true about  C Functions    ",["Functions need not return any value ","Functions must always return an integer ","Functions should always return a float","Functions Should always return more than one value "],1),
new Question("What is incorrect among the following options about recursive function?<br><br>A recursive function ----------   ",["calls itself"," is equivalent to a loop ","does not have a return value at all ","has a termination condition"],3),
new Question("Write the output of the following program<br><br><div class='codetext'>int main()<br>{<br>&nbsp;&nbsp;static i=3;<br>&nbsp;&nbsp;printf('%d',i--);<br>&nbsp;&nbsp;return i>0 ? main():0;<br>}<br></div>",["Error.  main can not be called recursively","Run time error","Infinitely prints 3","321"],4),
new Question("Which of the following return-type cannot be used for a function in C?   ",["char *","struct","void","Array"],4),
new Question("Which header file should you include if you are to develop a function that can accept variable number of arguments ?   ",["stdlib.h","vararg.h","stdio.h","stdarg.h"],4),
new Question("Which of the following statements are correct about the program?<br><br><br><div class='codetext'>#include<stdio.h><br>int main()<br>{<br>&nbsp;&nbsp;  printf('%p\n', main());<br>&nbsp;&nbsp;  return 0;<br>}<br></div>",["It prints garbage values infinitely","Runs infinitely without printing anything","Error: main() cannot be called inside printf()","No Error and prints nothing"],2),
new Question("A function must be enclosed in a pair of -----   ",["Round brackets","curly brackets","begin and end","None of the above"],2),
new Question("A function is written to find if the given number is prime. Find out errors if any.<br><br><div class='codetext'>int isPrime(int n)<br>{<br>&nbsp;&nbsp;  int i=2;<br>&nbsp;&nbsp;  if(n%i==0)<br>&nbsp;&nbsp;    return 0;<br>&nbsp;&nbsp;  for(i=3; i*i<=n;i+=2)<br>&nbsp;&nbsp;     if(n%i==0)<br>&nbsp;&nbsp;        return 0;<br>&nbsp;&nbsp;  return 1;<br>}<br>&nbsp;&nbsp;       <br></div>",["for loop must use i++, not i+=2","Condition in for loop must be i<n, not i*i<=n","A function can not have multiple return statements","No errors"],4),
new Question("A function can contain --- number of parameters   ",["0 or more","1 or more","1",""],1),
new Question("State whether true or false<br>When a C function is called the arguments provided to the function are modified by the function.   ",["true","false","",""],2),
new Question("A non-void function can return ------ values   ",["1","2","0 ","Any number"],1),
new Question("In the function <br>&nbsp;&nbsp; <div class='codetext'> float fn2(int a);</div>float indicates ---------   ",["Type of parameters to function","Type of return value of function","Type of local variables in function","None of the above"],2),
new Question("What does return statement do in a function?   ",["It terminates the function and returns a value","It returns to the begining of function","It terminates the function","None of the above"],1),
new Question("What is the output of the following code?<br><br><div class='codetext'>int square(int m)<br>{<br>&nbsp;&nbsp;  return m*m;<br>}<br>int main()<br>{<br>&nbsp;&nbsp; int i= 5;<br>&nbsp;&nbsp; square(i);<br>&nbsp;&nbsp; printf('%d',i);<br>}<br></div>",["25","5","Garbage value","None of the above"],2),
new Question("State whether the following line is true or false.<br><br>&nbsp;&nbsp;A void function can not have a return statement.   ",["true","false","",""],2),
new Question("A function is written to find whether a given character is upper case letter or not. Find out errors if any.<br><br><div class='codetext'>int isuppercase(char ch)<br>{<br>&nbsp;&nbsp;  if(ch>='A' &&ch<='Z')<br>&nbsp;&nbsp;     return 1;<br>&nbsp;&nbsp;  return 0;<br>}<br></div>",["The AND operator is  &","else is not used","Relational operators <= and >= can not be used with char variables","No errors"],4),
new Question("What is the output of the following code?<br><br><div class='codetext'>int fn1()<br>{<br>&nbsp;&nbsp;  printf('%d',a);<br>}<br>int main()<br>{<br>&nbsp;&nbsp;   int a = 100;<br>&nbsp;&nbsp;   fn1();<br>}<br></div>",["100","Garbage value","0 ","Syntax error"],4),
new Question("What does the following function do?<br><br><div class='codetext'>int fn(int n)<br>{<br>&nbsp;&nbsp; if(n>=1)<br>&nbsp;&nbsp;&nbsp;&nbsp;   return n*fn(n-1);<br>&nbsp;&nbsp;return 1;<br>}<br></div>",["It checks whether the number is positive.","It just returns 1","It finds factorial of a number","Syntax error because a function can not call itself"],3),
new Question("Which of the following is declaration of function   ",["<span class='codetext'>m = sum(n,p);</span>","<span class='codetext'>int sum(int a,int b)<br>{<br>&nbsp;&nbsp; return a+b;<br>}</span>","<span class='codetext'>int sum(int,int);</span>","All of the above"],3),
new Question("What does the function abc() return?<br><br><div class='codetext'>void abc()<br>{<br>&nbsp;&nbsp;  1<2?return 1:return 0;<br>}<br></div>",["1","2","Garbage value","Syntax error"],4),
new Question("Which keyword can be used to terminate a loop? And which keyword is used to terminate a function?   ",["break and continue","continue and break","break and return","None of the above"],3),
new Question("What is the output of the following program?<br><br><div class='codetext'>#include <stdio.h><br>int main()<br>{<br>&nbsp;&nbsp; static int num;<br>&nbsp;&nbsp; num++;<br>&nbsp;&nbsp; printf('In main ');<br>&nbsp;&nbsp; if(num<5)<br>&nbsp;&nbsp;    main();<br>}<br></div>",["main is called infinitely","in main is printed 5 times","Run time error","in main is printed once"],2),
new Question("A recursive function is the one ------   ",["Which is called multiple times","Which calls itself","Which should be used for factorial program","None of the above"],2),
new Question("What does the following function do?<br><br><div class='codetext'>int somefn(int *p1,int *p2, int n)<br>{<br>&nbsp;&nbsp;  int i;<br>&nbsp;&nbsp;  for(i=0;i<n;i++)<br>&nbsp;&nbsp;    if(*p1++!=*p2++)<br>&nbsp;&nbsp;       return 0;<br><br>&nbsp;&nbsp;return 1;<br>}<br></div>",["It compares two pointers","It compares two arrays","It gives syntax error","None of the above"],2),
new Question("Complete the code which should find if a sorted array has a value v in it. <br><br><div class='codetext'>for(i=0;i<n;i++)<br>&nbsp;&nbsp; if(--------)<br>&nbsp;&nbsp;    printf('%d is present in array',v);<br>&nbsp;&nbsp; else if(-------)<br>&nbsp;&nbsp;    break;<br><br></div>",["<span class='codetext'>a[i]==v and a[i]!=v</span>","<span class='codetext'>a[i]==v and a[i]!=v</span>","<span class='codetext'>a[i]==v and a[i]>v</span>","None of the above"],3),
];
 