 class Question {
 constructor(text, choices, answer,explanation){
    this.text = text;
    this.choices = choices;
    this.answer = choices[answer-1]; 
     if(explanation!==undefined)
       this.explanation = explanation;
    else
       this.explanation = null; 
  }
  isCorrectAnswer = function(choice) {	 
    return this.answer === choice;
  }
} 
var questions = [new Question("What is the output of this code?<br><br><div class='codetext'>int arr[3]={11,34,45};<br>int *ptr = arr;<br>printf('%d',*ptr+2);<br></div>",["13","45","Syntax error in line 2","None of the above"],1,"Dereference operator * has a higher precedence than + operator. So *ptr is evaluated first - which gives us 11, then 2 is added to it and giving the answer of 13."),
new Question("Write output of the code.<br><br><div class='codetext'>int *ptr;<br>*ptr = 12;<br>printf('%d',*ptr);<br></div>",["12","Garbage Value","Syntax error in line 2","Run time error - Segmentation fault"],4,"The program tries to dereference a pointer which is not pointing at a valid location.<br>ptr is uninitialized, so it has some random address. *ptr will try to access the value at that address - which is not allowed. That is why, the program generates a run time error - segmentation fault.<br>A pointer should always be initialized with address of a variable, or it must be allocated using malloc, before it is dereferenced."),
new Question("What does this function do?<br><br><div class='codetext'>void foo(char *str1,char *str2)<br>{<br> &nbsp;&nbsp;   while(*str2++=*str1++);<br>}<br></div>",["Syntax error in while loop","While loop repeats 0 times, hence function does nothing","Copies the string str1 to str2","None of the above"],3,"Statement to be executed is in the conditional expression of while loop - *str2++=*str1++. This copies *str1 to *str2. Then increments both str1 and str2. This is repeated until it becomes false or 0. When *str1 is 0 or null character (terminating character of a string), it is copied to *str2 so that str2 is also null terminated and the loop ends.<br> So the entire string str1 is copied to str2."),
new Question("Which statement in this code is incorrect?<br><br><div class='codetext'>int main()<br>{<br>&nbsp;&nbsp;&nbsp; void *ptr;<br>&nbsp;&nbsp;&nbsp; int a = 10;<br>&nbsp;&nbsp;&nbsp; ptr = &a;<br>&nbsp;&nbsp;&nbsp; *ptr = 15;<br>&nbsp;&nbsp;&nbsp; printf('%d',*ptr);<br>}<br></div>",["void *ptr;","ptr = &a;","*ptr=15;","All of these."],3),
new Question("Which statement correctly defines an array of 10 integer pointers?<br><br> ",["int *ptr;","int *ptr[10];","int (*ptr)[10];","int(*ptr)(int[10]);"],2),
new Question("What does the following C statement declare?<br><br><div class='codetext'>int(*ptr)(int *);<br></div>",[" A function that takes an integer pointer as argument and returns an<br>integer"," A function that takes an integer as argument and returns an integer<br>pointer","A pointer to a function that takes an integer pointer as argument and returns an integer."," A function that takes an integer pointer as argument and returns a<br>function pointer"],3),
new Question("In the following code, which are the two statements that produce syntax error and  run time error?<br><br><div class='codetext'>char arr[]='Hello';<br>char *ptr='Hello';<br>arr[1]='i';  ptr[1]='i';<br>arr='hi';&nbsp;&nbsp;&nbsp;ptr='hi';<br></div>",["<span class='monotext'>arr='hi'; </span> and <span class='monotext'>ptr='hi';</span>","<span class='monotext'>arr[1]='i'; </span>and <span class='monotext'>ptr[1]='i';</span>","<span class='monotext'> arr='hi';</span>    and <span class='monotext'>ptr[1]="+"'"+"i"+"';</span>","None of these"],3),
new Question("What is the error in this code?<br><br><div class='codetext'>char *p;<br>*p = malloc(10);<br></div>",["No error","Memory should be allocated to p, not *p","Memory can not be allocated to char pointers","None of these"],2),
new Question("What is the output of this code?<br><br><div class='codetext'>int array[5], i, *ip;<br>for(i = 0; i < 5; i++)<br>&nbsp;&nbsp;&nbsp;array[i] = i;<br>ip = array;<br>printf('%d\n', *(ip + 3 * sizeof(int)));<br></div>",["3","9","Garbage value","Syntax error"],3),
new Question("A function is written to initialize an integer pointer. Find out errors if any.<br><br><div class='codetext'>void memory_allocate(int *ptr)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ptr = (int*)malloc(sizeof(int)*100);<br>}<br>int main()<br>{<br>&nbsp;&nbsp;&nbsp; int *ptr1 ;<br>&nbsp;&nbsp;&nbsp; memory_allocate(ptr1);<br>&nbsp;&nbsp;&nbsp; *ptr1 = 12;<br>    &nbsp;&nbsp;&nbsp;------<br>}<br></div>",["The function should return the pointer after allocating memory","No errors","",""],1),
new Question(" In this case, how do you assign square function to the function pointer fptr in the code given below?<br><br><div class='codetext'>int (*fptr)(int);<br>int square(int n);<br></div>",["fptr = &"+"square ;","fptr = square;","fptr = square(2);","Both 1 and 2"],4),
new Question("How is NULL pointer defined?<br><br> ",["(void*)0","(int*)0","NULL  is wrong. It is null","None of these"],1),
new Question("Is the following code correct in verifying pointer is not NULL before dereferncing the pointer?<br><br><div class='codetext'>if(ptr)<br>*ptr = 12;<br></div>",["Correct","Incorrect","",""],1),
new Question("What is the error in following code?<br><br><div class='codetext'>int *ptr;<br>ptr =(int *)malloc(100);<br>------<br>free(ptr);<br>m  = *ptr+1;<br></div>",["No error","Usage of a dangling pointer","",""],2),
new Question("Which of the following functions will allocate memory and initialize them with 0?<br><br> ",["malloc()","calloc()","free()","Both 1 and 2"],2),
new Question("How do you define a pointer to an array of 10 integers?<br><br> ",["int *ptr[10];","int (*ptr)[10];","int (*ptr)(10);","None of these"],2),
new Question("What will be the output of this code?<br><br><div class='codetext'>char *p,q;<br>char ch = &#39;A&#39;;<br>q = &ch;     *q=&#39;B&#39;;<br>printf('%c',ch);<br></div>",["B","A","Syntax Error",""],3),
new Question("Is the following statement true or false?<br><br>Pointers enable a C program to simulate call by value<br><br> ",["true","false","",""],2),
new Question("The complement of & operator(address of) is --------<br><br> ",["|","&&","*","None of these"],3),
new Question("What is the output of this C code?<br><br><div class='codetext'> int mul(int a, int b, int c)<br> {<br>return a * b * c;<br>}<br>int main()<br>{<br>  int (*fptr)(int, int, int);&nbsp;&nbsp;&nbsp;fptr  =  mul;<br>  printf('The product is:%d',  fptr(2, 3, 4));<br>}<br></div>",["The product is 24","Run time error","Nothing","Depends on compiler"],1),
new Question("What does  the following declaration define?<br><br><div class='codetext'>int (*pf)();<br></div>",["pf is a function which returns an integer pointer","pf is a pointer to a function which takes no parameters and returns int","pf is a function  which takes an int pointer parameter.",""],2),
new Question("Find out errors in the code<br><br><div class='codetext'>int a[] = {10, 20, 30, 40, 50, -1};<br>int* b = malloc(sizeof(a));<br>memcpy(b, a, sizeof(a));<br>if ( a == b )<br>&nbsp;printf('Equal\n');<br>else<br>&nbsp; printf('Not equal\n');<br>free(a);<br>free(b); <br></div>",["We must not compare arrays using == operator","free a is wrong, since a is not allocated memory ","Both 1 and 2","No error"],3),
new Question("With every use of a memory allocation functions, which function should be used to release allocated memory which is no longer needed?<br><br> ",["unalloc()","dealloc()","release()","free()"],4),
new Question("What is the type of foo in the following declaration?<br><br><br><div class='codetext'>void *(*foo)(int *)<br></div>",["A function taking integer pointer as argument and returning a void pointer","A function taking int pointer as argument and returning void","A pointer to function which takes integer pointer as argument and returns a void pointer",""],3),
new Question("Write the output of the following program.<br><br><div class='codetext'> int main()<br>{<br>&nbsp;&nbsp;&nbsp;  int i; float *pf;<br>&nbsp;&nbsp;&nbsp;  pf = (float *)&i;<br>&nbsp;&nbsp;&nbsp;  *pf = 100.00;<br>&nbsp;&nbsp;&nbsp;  printf('%d', i);<br>}<br></div>",["Run time error","100","Some integer but not 100",""],3),
new Question("Declare a pointer to a function that takes a char pointer as argument and returns a void pointer. <br><br> ",["void *(*fptr)(char *)","void *fptr(char *);","void *(*fptr,char*);",""],1),
new Question("What will be stored in str after this code is run?<br><br><div class='codetext'>char *str;<br>char *str1='Hello World';<br>sscanf(str1,'%s',str);<br></div>",["Hello world","Syntax error in sscanf","Hello","Run time error"],4),
new Question("What is (void*)0?<br> 	<br><br> ",["Representation of NULL pointer","Representation of void pointer","Error","None of above"],1),
new Question("What will be the output of the program ?<br><br><div class='codetext'>int main()<br>{<br>&nbsp;&nbsp;&nbsp; char *s= 'peace';<br>&nbsp;&nbsp;&nbsp; printf('%s\n', s++ +3);<br>&nbsp;&nbsp;&nbsp; return 0;<br>}<br></div>",["peace","eace","ace","ce"],4),
new Question("What is x in the following program?<br><br><div class='codetext'>int main()<br>{<br>&nbsp;&nbsp;&nbsp; typedef char (*(*arrfptr[3])())[10];<br>&nbsp;&nbsp;&nbsp; arrfptr x;<br>&nbsp;&nbsp;&nbsp; return 0;<br>}<br></div>",["x is a pointer","x is an array of three pointers","x is an array of three function pointers which return pointer to an array of 10 characters","Error in x declaration"],3),
new Question("What is the output of this code?<br><br><div class='codetext'>int a=10,b;<br>b=a;<br>int *ptr = &a;<br>*a=15;<br>printf('%d %d',a,b);<br></div>",["10 10","15 15","15 10",""],3),
new Question("What is the output of this code?<br><br><div class='codetext'>int arr[]={1,2,3,4,5,6};<br>int *ptr = arr;<br>int i;<br>for(i=0;i<3;i++,ptr+=2)<br>  printf('%d',*ptr);<br></div>",["1 2 3 4 5 6","1 1 1","1 3 5","Run time error"],3),
new Question("What is the output of this code?<br><br><div class='codetext'>char *ptr[]={'char','double','float','int'};<br>int i;<br>ptr[0]='string';<br>ptr[1][0]='D';<br>for(i=0;i<4;i++)printf('%s  ',ptr[i]);<br></div>",["char double float int","string Double float int","Syntax error in the line.   ptr[0]='string';","Runtime error from line  ptr[1][0]='D';"],4),
new Question("What is the output of this code?<br><br><div class='codetext'>int *ptr;<br>int arr[3][3]={1,2,3,4,5,6,7,8,9};<br>int i,j;<br>for(i=0;i<3;i++)<br>{<br>  ptr = arr[i];<br>  for(j=0;j<3;j++)<br>&nbsp;&nbsp;&nbsp; printf('%d ',*ptr++);<br>}<br></div>",["Syntax Error. ptr can not point to 2 dimensional array","1 2 3","1 2 3 4 5 6 7 8 9",""],3),
new Question("What is the output of this code?<br><br><div class='codetext'>char *str = 'Hello';<br>while(*str)<br>&nbsp;&nbsp;&nbsp;putchar(*str++);<br></div>",["Infinite loop ","Syntax error","Hello",""],3),
new Question("What does this function do?<br><br><div class='codetext'>void string_reverse(char *str)<br>{<br>&nbsp;&nbsp;&nbsp;int i,j;i=0;j=strlen(str)-1;<br>&nbsp;&nbsp;&nbsp;for(i=0;i&lt;strlen(str);i++,j--)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; char temp=str[i];<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; str[i]=str[j];<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  str[j]=temp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>}<br></div>",["Reverses the string","Prints the string in reverse order","Does not reverse string",""],3),
new Question("What is the output of this program?<br><br><div class='codetext'>#include&lt;stdio.h&gt;<br>int main()<br>{<br>&nbsp;&nbsp;&nbsp;int arr[]= {10,20,30,40,50};<br>&nbsp;&nbsp;&nbsp;char *ptr = (char *)arr;<br>&nbsp;&nbsp;&nbsp;printf('%d',*((int*)ptr+3));<br>&nbsp;&nbsp;&nbsp;printf(' %d',*(int*)(ptr+4));<br>&nbsp;&nbsp;&nbsp;return 0;<br>}<br></div>",["30 40","30 20","40 20","None of the above"],3),
new Question("What are the errors in the following program if any?<br><br><div class='codetext'>#include&lt;stdio.h&gt;<br>int main()<br>{<br>&nbsp;&nbsp;&nbsp;  int arr[]={10,20,30,40};<br>&nbsp;&nbsp;&nbsp;  int i;<br>&nbsp;&nbsp;&nbsp;  for(i=0;i<4;i++)<br>&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  printf('%d ',*arr);<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  arr++;<br>&nbsp;&nbsp;&nbsp; }<br>&nbsp;&nbsp;&nbsp; return 0;<br>}<br></div>",["An array can not be initialized in its declaration statement","for loop should be<br>for(i=1;i<=4;i++)","arr being an array, it can not be incremented","No errors"],3),
new Question("What is the correct way of setting the address of a to the pointer ptr in the following code?<br><br><div class='codetext'>int a=3;<br>int *ptr;<br></div>",["*ptr = a;","ptr = a","ptr = &a;","None of the above"],3),
new Question("What is the output of the following code?<br><br><div class='codetext'>int *ptr;<br>int **ptr2;<br>int ***ptr3;<br>int a=3;<br>ptr = &a;<br>ptr2 = &ptr;<br>ptr3=&ptr2;<br>printf('%d %d %d',***ptr3,**ptr2,*ptr);<br></div>",["Syntax error. Too many indirection operators","Some address repeated thrice","3 3 3","None of the above"],3),
new Question("What is a void pointer in C?<br><br> ",["A pointer which can point any type of variable","A pointer which can not be dereferenced without typecasting","A pointer to void","Both 1 and 2"],4),
new Question("A NULL pointer is ------<br><br> ",["A generic pointer","A pointer pointing to address 0","Both 1 and 2",""],2),
new Question("Memory is allocated at run time in C using ------ and released using -----<br><br> ",["malloc and unalloc","malloc and calloc","malloc and free","None of the above"],3),
new Question("What causes memory leakage in a program?<br><br> ",["Too much memory allocation","Allocating memory for very large strings","Not releasing the memory which was allocated earlier","Any of the above"],3),
new Question("What does the following code print?<br><br><div class='codetext'>int *ptr;<br>int a =10;<br>*ptr = &a; <br>printf('%d',*ptr);<br></div>",["10","0","Run time error","None of the above"],3),
new Question("<div class = 'codetext'>void print_matrix(------){}<br>int main()<br>{<br>&nbsp;&nbsp;int a[4][4];<br>&nbsp;&nbsp;print_matrix(a);<br>&nbsp;}</div><br>In the code above how  should the header of print_matrix function be defined?",["void print_matrix(int a[][4])","void print_matrix(int **)","void print_matrix(int (*)[4])","none of the above"],3),
new Question("What is the output of the following program?<br><br><div class='codetext'>#include&lt;stdio.h&gt;<br>#include&lt;stdlib.h&gt;<br>int main()<br>{<br>&nbsp;&nbsp;&nbsp;char *ptr;<br>&nbsp;&nbsp;&nbsp;ptr = 'Hello world';<br>&nbsp;&nbsp;&nbsp;puts(ptr);<br>&nbsp;&nbsp;&nbsp;free(ptr);<br>&nbsp;&nbsp;&nbsp;return 0;<br>}<br></div>",["Hello world","Syntax error","Hello world and then program crashes","None of the above"],3),
];
 