let qnArray=[ ["A machine in a soft drink factory fills 840 bottles in six hours. How many bottles will it fill in five hours?",700,800,500,1000],
["A photograph of a bacteria enlarged 50,000 times attains a length of 5 cm. If the photograph is enlarged 20,000 times only, what would be its enlarged length?",2,10,1,5],
["In a model of a ship, the mast is 9 cm high, while the mast of the actual ship is 12 m high. If the length of the ship is 28 m, how long is the model ship?",21,28,12,9],
["Suppose 2 kg of sugar contains 9 × 10<sup>6</sup> crystals. How many sugar crystals are there in  5 kg of sugar?",
4.5e7,5e7,45,10],
["Rashmi has a road map with a scale of 1 cm representing 18 km. She drives on a road for 72 km. What would be her distance covered in the map?",4,72,18,6],
["A 5 m 60 cm high vertical pole casts a shadow 3 m 20 cm long. Find at the same time  the height of a pole which casts a shadow 5m long.",8.75,8,7,3.20],
["A loaded truck travels 14 km in 25 minutes. If the speed remains the same, how far can it travel in 5 hours?",168,150,2.4,24],
["If a box of sweets is divided among 24 children, they will get 5 sweets each. How many would each get, if the number of the children is reduced by 4?",6,1,3,10],
["A farmer has enough food to feed 20 animals in his cattle for 6 days. How long would the food last if there were 10 more animals in his cattle?"],
["A contractor estimates that 3 persons could rewire Jasminder’s house in 4 days. If, he uses 4 persons instead of three, how long should they take to complete the job?"],
["A batch of bottles were packed in 25 boxes with 12 bottles in each box. If the same batch is packed using 20 bottles in each box, how many boxes would be filled?"],
["A factory requires 42 machines to produce a given number of articles in 63 days. How many machines would be required to produce the same number of articles in 54 days?"],
["A car takes 2 hours to reach a destination by travelling at the speed of 60 km/h. How long will it take when the car travels at the speed of 80 km/h?"],
["A school has 8 periods a day each of 45 minutes duration. How long would each period be, if the school has 9 periods a day, assuming the number of school hours to be the same?"],
]
let solnArray=["Time required to fill and number of bottles are directly proportional to each other.<br>so 840/6 = x/5 <br> x = 840*5/6 = 700",
"Let x be length of bacteria when enlarged 20,000 times<br> 5/50000 = x/20000<br>x = 5/50000*20000=2",
"The model ship is to scale. If x is the length of model ship  then<br>9/1200 = x/2800<br> x- 9/1200*2800=36cm",
"9*10<sup>6</sup>/2 = x/5<br>x = 9*10<sup>6</sup>/2 *5=4.5*10<sup>7</sup>",
"Let the distance be x. <br>As the distance on road and map are directly proportional, 1/18=x/72<br>x = 72/18=4cm",
"Let the shadow length be x.<br>560/320=x/500<br>x=560*500/320=875<br>The shadow is 8.75 meters long",
"Let the distance travelled n 5 hours be xkm. <br>14/25 = x/(60*5)<br> x=14*60*5/25 = 168km",
"The number of sweets and number of children are in inverse proportions.<br>If number of children is reduced by 4, it will be 20<br>24*5 = 20*x<br>x = 24*5/20=6",
"
]
